### ISSUE TITLE
`onvif-cli` does not work

### ISSUE THREAD

**Issue by wpyoga** [openvideolibs/python-onvif-zeep-async#74]
The README mentions the existence of `onvif-cli`, but it does not work.

What I did, at first:
1. Create a virtual environment
1. Install onvif-zeep-async inside the virtual environment with `pip3 install onvif-zeep-async`
1. Call onvif-cli

This is the output on my terminal:
```
(venv) william@x99:~/p$ onvif-cli
Traceback (most recent call last):
  File "/home/william/p/venv/bin/onvif-cli", line 5, in <module>
    from onvif.cli import main
ModuleNotFoundError: No module named 'onvif.cli'
```

I also tried the other method mentioned in the README, but with a virtual environment:
1. Create a virtual environment
1. Clone this repo
1. Install this package inside the virtual environment with `python setup.py install`
1. Call onvif-cli

This is the output I get:
```
(venv) william@x99:~/python-onvif-zeep-async$ onvif-cli
Traceback (most recent call last):
  File "/home/william/python-onvif-zeep-async/venv/bin/onvif-cli", line 33, in <module>
    sys.exit(load_entry_point('onvif-zeep-async==3.1.13', 'console_scripts', 'onvif-cli')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/william/python-onvif-zeep-async/venv/bin/onvif-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'onvif.cli'
```

Now, I'm not very familiar with Python CLI tool development, but I should be able to contribute code if someone can give me a pointer here.

**Comment by bdraco** [comment]
This lib was forked from another project which had a CLI. Its left-overs and doesn't actually exist
